// <auto-generated />
using System;
using MathWorldAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MathWorldAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720170000_AddProblemAttemptTracking")]
    partial class AddProblemAttemptTracking
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MathWorldAPI.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MathWorldAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "🔢",
                            NameAr = "الأعداد والعمليات الحسابية",
                            NameEn = "Numbers & Operations",
                            Order = 1,
                            StageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Icon = "🧩",
                            NameAr = "التفكير الجبري المبكر",
                            NameEn = "Early Algebraic Thinking",
                            Order = 2,
                            StageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Icon = "📏",
                            NameAr = "الهندسة والقياس",
                            NameEn = "Geometry & Measurement",
                            Order = 3,
                            StageId = 1
                        },
                        new
                        {
                            Id = 4,
                            Icon = "📊",
                            NameAr = "البيانات والاحتمالات",
                            NameEn = "Data & Basic Probability",
                            Order = 4,
                            StageId = 1
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🔬",
                            NameAr = "نظرية الأعداد والأسس",
                            NameEn = "Number Theory & Exponents",
                            Order = 1,
                            StageId = 2
                        },
                        new
                        {
                            Id = 6,
                            Icon = "⚖️",
                            NameAr = "الجبر والدوال",
                            NameEn = "Algebra & Functions",
                            Order = 2,
                            StageId = 2
                        },
                        new
                        {
                            Id = 7,
                            Icon = "💹",
                            NameAr = "النسب والتناسب",
                            NameEn = "Ratios & Proportions",
                            Order = 3,
                            StageId = 2
                        },
                        new
                        {
                            Id = 8,
                            Icon = "📐",
                            NameAr = "الهندسة والبراهين",
                            NameEn = "Geometry & Proofs",
                            Order = 4,
                            StageId = 2
                        },
                        new
                        {
                            Id = 9,
                            Icon = "📈",
                            NameAr = "الجبر المتقدم",
                            NameEn = "Advanced Algebra",
                            Order = 1,
                            StageId = 3
                        },
                        new
                        {
                            Id = 10,
                            Icon = "📐",
                            NameAr = "حساب المثلثات",
                            NameEn = "Trigonometry",
                            Order = 2,
                            StageId = 3
                        },
                        new
                        {
                            Id = 11,
                            Icon = "∫",
                            NameAr = "التفاضل والتكامل",
                            NameEn = "Calculus",
                            Order = 3,
                            StageId = 3
                        },
                        new
                        {
                            Id = 12,
                            Icon = "🎲",
                            NameAr = "الإحصاء والاحتمالات المتقدم",
                            NameEn = "Advanced Statistics",
                            Order = 4,
                            StageId = 3
                        },
                        new
                        {
                            Id = 13,
                            Icon = "🌌",
                            NameAr = "التفاضل متعدد المتغيرات",
                            NameEn = "Multivariable Calculus",
                            Order = 1,
                            StageId = 4
                        },
                        new
                        {
                            Id = 14,
                            Icon = "🧮",
                            NameAr = "الجبر الخطي",
                            NameEn = "Linear Algebra",
                            Order = 2,
                            StageId = 4
                        },
                        new
                        {
                            Id = 15,
                            Icon = "🌀",
                            NameAr = "المعادلات التفاضلية",
                            NameEn = "Differential Equations",
                            Order = 3,
                            StageId = 4
                        },
                        new
                        {
                            Id = 16,
                            Icon = "∞",
                            NameAr = "التحليل الحقيقي",
                            NameEn = "Real Analysis",
                            Order = 4,
                            StageId = 4
                        });
                });

            modelBuilder.Entity("MathWorldAPI.Models.EducationalStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EducationalStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "المرحلة الابتدائية",
                            NameEn = "Elementary School",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "المرحلة الإعدادية",
                            NameEn = "Middle School",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "المرحلة الثانوية",
                            NameEn = "High School",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "المرحلة الجامعية",
                            NameEn = "University",
                            Order = 4
                        });
                });

            modelBuilder.Entity("MathWorldAPI.Models.MathProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailedSolutionAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailedSolutionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionTextAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionTextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer");

                    b.Property<string>("YoutubeSolutionUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StageId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("MathWorldAPI.Models.ProblemAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectOptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedOptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("UsedHint")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId", "ProblemId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("UserId", "SubmittedAt");

                    b.ToTable("ProblemAttempts");
                });

            modelBuilder.Entity("MathWorldAPI.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("LatexCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "Order")
                        .IsUnique();

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("MathWorldAPI.Models.SocialLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderId")
                        .IsUnique();

                    b.ToTable("SocialLogins");
                });

            modelBuilder.Entity("MathWorldAPI.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<int?>("BestTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveCorrectReviews")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("FirstAttemptCorrect")
                        .HasColumnType("boolean");

                    b.Property<int?>("FirstSelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("IncorrectAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsErrorNotebookArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInErrorNotebook")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MasteryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("New");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<long>("TotalTimeSpentSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId", "IsInErrorNotebook", "IsErrorNotebookArchived");

                    b.HasIndex("UserId", "NextReviewAt");

                    b.HasIndex("UserId", "ProblemId")
                        .IsUnique();

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("MathWorldAPI.Models.Category", b =>
                {
                    b.HasOne("MathWorldAPI.Models.EducationalStage", "Stage")
                        .WithMany("Categories")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("MathWorldAPI.Models.MathProblem", b =>
                {
                    b.HasOne("MathWorldAPI.Models.Category", "Category")
                        .WithMany("Problems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathWorldAPI.Models.EducationalStage", "Stage")
                        .WithMany("Problems")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("MathWorldAPI.Models.ProblemAttempt", b =>
                {
                    b.HasOne("MathWorldAPI.Models.MathProblem", "Problem")
                        .WithMany("ProblemAttempts")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathWorldAPI.Models.AppUser", "User")
                        .WithMany("ProblemAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathWorldAPI.Models.QuestionOption", b =>
                {
                    b.HasOne("MathWorldAPI.Models.MathProblem", "Problem")
                        .WithMany("Options")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("MathWorldAPI.Models.SocialLogin", b =>
                {
                    b.HasOne("MathWorldAPI.Models.AppUser", "User")
                        .WithMany("SocialLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathWorldAPI.Models.UserProgress", b =>
                {
                    b.HasOne("MathWorldAPI.Models.MathProblem", "Problem")
                        .WithMany("UserProgresses")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathWorldAPI.Models.AppUser", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathWorldAPI.Models.AppUser", b =>
                {
                    b.Navigation("ProblemAttempts");

                    b.Navigation("SocialLogins");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("MathWorldAPI.Models.Category", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("MathWorldAPI.Models.EducationalStage", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Problems");
                });

            modelBuilder.Entity("MathWorldAPI.Models.MathProblem", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("ProblemAttempts");

                    b.Navigation("UserProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
